---
- name: Resource present eventually
  k8s:
    state: present
    namespace: "{{ oc_project }}"
    definition: "{{ resource }}"
    validate_certs: false  # <-- FixMe
  register: resource_present
  until: resource_present is success or resource_present.status|default(0) != 404
  delay: 30
  retries: 6
  async: 120
  poll: 0
  vars:
    ansible_async_dir: /ansible/.ansible/async-present-{{ item|regex_replace('/','-') }}
  with_items: # <- Display Only
    - "{{ resource.kind }}/{{ resource.metadata.name }}"
  notify: Wait for resource to be present

- name: Storing handled resource name
  set_fact:
    present_resource: "{{ resource.kind }}/{{ resource.metadata.name }}"
