---
- name: Resource removed
  k8s:
    state: absent
    namespace: "{{ oc_project }}"
    kind: "{{ resource.kind }}"
    name: "{{ (app_existing_resource|from_yaml).metadata.name }}"
    validate_certs: false  # <-- FixMe
  register: resource_removal
  async: 120
  poll: 0
  vars:
    ansible_async_dir: /ansible/.ansible/async-remove-{{ item|regex_replace('/','-') }}
  with_items: # <- Display Only
    - "{{ resource.kind }}/{{ (app_existing_resource|from_yaml).metadata.name }}"
  notify: Wait for resource removal

- name: Storing removed resource name
  set_fact:
    removed_resource: "{{ resource.kind }}/{{ (app_existing_resource|from_yaml).metadata.name }}"
